<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- Reference only the DLL file, not the project -->
    <Reference Include="ZplRenderer">
      <HintPath>..\..\ZplRenderer\bin\Debug\net40\ZplRenderer.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
